### ISSUE TITLE
Breaking change: support new AST shape defined in estree/experimental

### ISSUE THREAD

**Issue by JLHwung** [acornjs/acorn-class-fields#15]
Now that class features reaches stage 3 and shipped in many browsers, people begin trying on this feature. It will be great if acorn can implement https://github.com/estree/estree/blob/master/experimental/class-features.md (even in a stage 3 plugin) so `@babel/eslint-parser` can align to that AST shape, too.

Lesson from optional chaining: The earlier we begin to work on consensual AST shape, the less the friction we introduced to the communities.

Context: https://github.com/babel/babel/issues/12282

**Comment by tchetwin** [comment]
I have a series of changes locally (starting with https://github.com/acornjs/acorn-private-class-elements/pull/16) to address this divergence in the ASTs
