### ISSUE TITLE
feature-request: add support for private methods

### ISSUE THREAD

**Issue by iShibi** [acornjs/acorn-class-fields#17]
⚠️ Note: I've no knowledge of how this library works, I got some issues with [vitest](https://github.com/vitest-dev/vitest) and was redirected to here.

Vitest isn't able to parse the `#` symbol of `#private` fields in a class. It seems that vitest uses this plugin under the hood, so it would be great if you can add support for private methods.

I've created an mcve for this issue that you can find here: [stackblitz.com/edit/node-stkuzb](https://stackblitz.com/edit/node-stkuzb)

**Comment by tchetwin** [comment]
As of Acorn 8.2.0 private fields and private methods are supported in Acorn without the need to use this (or another) plugin, I recommend upgrading Acorn.

**Comment by iShibi** [comment]
thanks, I'll let them know about it 👍
