### ISSUE TITLE
Call to acorn-private-class-elements fails with "does not support mixing different acorn copies"

### ISSUE THREAD

**Issue by 0biWanKenobi** [acornjs/acorn-class-fields#7]
Currently using is as a rollup plugin, with rollup 2.1.0. 

### Expected behaviour:

rollup bundling works

### Actual behaviour:

acorn-class-fields fails in `index.js` at line 17:
`Parser = privateClassElements(Parser)`

and this Error is thrown:

`[!] Error: acorn-private-class-elements does not support mixing different acorn copies
Error: acorn-private-class-elements does not support mixing different acorn copies`

### Proposed solution

This happens because `acorn-private-class-elements` expects the `Parser` object from `acorn`, so calling it like this

`Parser = privateClassElements(acorn.Parser)`

solved the issue for me. I hope I'm on the right track and that this can be fixed! Cheers :)

**Comment by adrianheine** [comment]
Should be fixed in 0.3.2 with f6818530866b6a557087d9b4608bac0dd90abdf5.
