### ISSUE TITLE
Parse error when "super" is used

### ISSUE THREAD

**Issue by lukastaegert** [acornjs/acorn-class-fields#9]
Originally via rollup/rollup#3505, which bundles this plugin at the moment:

It is not possible to use `super` in class properties even though it probably should, at least according to https://2ality.com/2019/07/public-class-fields.html#the-scope-of-field-initializers (I know this is not official documentation...)

At the moment the following throws with a `SyntaxError: 'super' keyword outside a method`:

```js
require('acorn')
  .Parser.extend(require('acorn-class-fields'), require('acorn-static-class-features'))
  .parse('class SubClass extends SuperClass { prop = super.getValue(); }');
```

**Comment by lukastaegert** [comment]
cc @guybedford Apparently I cannot create an issue in your fork

**Comment by pschroen** [comment]
I should add `super` works as expected in Chrome with the reference link example.

Tested with Version 81.0.4044.113.

**Comment by guybedford** [comment]
Ok I've added a fix in https://github.com/guybedford/acorn-class-fields/commit/8a1fe764b9588872013418e8d4335de88ad038aa. Apparently I am now maintaining this :P No guarantees going forward.....

**Comment by adrianheine** [comment]
Fixed in #8.

**Comment by guybedford** [comment]
@adrianheine note that #8 was a different PR to the changes in https://github.com/guybedford/acorn-class-fields/commit/8a1fe764b9588872013418e8d4335de88ad038aa. If you would like me to turn that commit into a PR here I can do that though.

This issue should likely remain open until that is merged.

**Comment by adrianheine** [comment]
No, you pushed 8a1fe764b9588872013418e8d4335de88ad038aa to that branch and I merged it.

**Comment by guybedford** [comment]
Ah great, I actually didn't even realise my fork branch and that PR branch were the same one.

Much appreciated for merging these fixes!
